version: '3.8'

services:
  backend:
    build:
      context: ./fitbacker-backend
    ports:
      - "5000:5000"
    env_file:
      - ./fitbacker-backend/.env
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./fitbacker-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./fitbacker-frontend/.env

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo-data:
