version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - '27017:27017'
    volumes:
      - mongodbdata:/data/db

  backend:
    build: .
    container_name: backend-container
    env_file: .env
    ports:
      - '5000:5000'
    depends_on:
      - mongodb

volumes:
  mongodbdata:
    driver: local
